### ISSUE TITLE
How many winners and runners up will there be?

### ISSUE THREAD

**Issue by roryokane** [github/game-off-2012#10]
You have 5 iPads to give to the winners – does that mean there will be 5 winners? And how many runners up will there be?

**Comment by leereilly** [comment]
We'll have 5 winners and _at least_ 5 runners up.

Cheers,
  Lee :beers:

**Comment by shalecraig** [comment]
[subscribing]

**Comment by roryokane** [comment]
@shalecraig You don’t need to comment to subscribe to a thread. Below the comment form, you should see this button:

![GitHub button to watch a thread](http://i.imgur.com/TPEPk.png)

**Comment by shalecraig** [comment]
Wow, I completely missed that.

I didn't see one at the top, so I assumed it didn't exist.
