### ISSUE TITLE
Can we play with Git/GitHub concepts ?

### ISSUE THREAD

**Issue by pelostudio** [github/game-off-2012#11]
Hi there,

I understood that we have to use some of the ideas behind Git, but can we actually make a game that involves Git or GitHub itselves ?

An example might be, you have to make some kind of pull request to a specific repository or anything. I understand that GitHub itself may not be a place for games but I wanted to be sure.

Best.

**Comment by leereilly** [comment]
Hi there,

That sounds very interesting! I'd support that as long as long as it didn't abuse existing repos with issues, pull requests,  etc.

I'm not sure if you're familiar with any of these, but there are a few sites/apps adding a sort of "gamification" to Git/GitHub already e.g. [Coderwall](http://coderwall.com/leereilly),  [GitScore](http://gitscore.com/user/defunkt) and [Git Achievements](https://github.com/icefox/git-achievements) to name but a few. 

 Can't wait to see what you come up with! Be sure to check out the [GitHub API](http://developer.github.com/v3/) for some possible ideas.

Cheers,
  Lee :beers:

**Comment by RylandAlmanza** [comment]
Would something like this work?

"What about a world building game, where the world data is split amongst lots of files and the process of forking/pulling/etc allows a collaboration of the building of the world

and if the client that allows you to view the world just requires a github repo url, then you can trivially share worlds"

Idea is from this TIGForum thread: http://forums.tigsource.com/index.php?topic=29254.0
