### ISSUE TITLE
QML Entries

### ISSUE THREAD

**Issue by noatlas** [github/game-off-2012#12]
Is QML an acceptable language for content entry?

**Comment by leereilly** [comment]
Do you mean Qt Meta Language/  Qt Modeling Language, or Quest Markup Language? 

I'm assuming it's the latter, which I _think_ is fine after reading the [FAQ](http://www.questml.com/faq.htm). As long as the source is available in your forked repository, and there's a URL when you can see it in action then that's fine.

Assuming this is for a text adventure, I can't wait to see it. I may have every single [Fighting Fantasy](http://www.fightingfantasy.com/) book ever created :metal:

Cheers,
  Lee :beers:
