### ISSUE TITLE
Is judging based on code quality or funness of game?

### ISSUE THREAD

**Issue by purpleladydragons** [github/game-off-2012#13]
Will we be judged on the quality of code, or on other things? Will there be different categories for winners, like most creative, smallest game, etc.?

**Comment by roryokane** [comment]
Issue #7 already asks what judging will be based on. That Issue doesn’t ask whether there are multiple categories for winners, though, so that can be answered here.

**Comment by leereilly** [comment]
Thanks for stepping in @roryokane! Short answer is **yes**, there'll be multiple categories and I will most likely **not** be judging actual code. More details in #7 if you don't mind popping in there.

Cheers,
  Lee :beers:
