### ISSUE TITLE
Has the competition started?

### ISSUE THREAD

**Issue by zzzev** [github/game-off-2012#15]
In the description of the challenge, it says "You have the entire month of November..."

Are we supposed to wait until Nov. 1st to begin (a la Ludum Dare)?

**Comment by leereilly** [comment]
I should clarify that. Yeah, you can start now :)

Cheers,
  Lee :beers:

**Comment by zzzev** [comment]
Thanks! Sorry for the overly literal-minded question, but well, I am a programmer.

**Comment by leereilly** [comment]
No problem! If you have this question, hundreds/thousands more will as well. I'm going to reopen this just so it stays on the unfiltered list of issues :metal:
