### ISSUE TITLE
When is this game due?

### ISSUE THREAD

**Issue by steven-schronk** [github/game-off-2012#16]
Maybe I don't see it but there does not seem to be a finish date.

Thanks for your help.

**Comment by haeric** [comment]
In the instructions:

> Make sure your code is pushed to the master branch of your forked repository before Dec 1st!

:)

**Comment by leereilly** [comment]
Thanks @haeric :smiley:

I'll make a couple of revisions to make sure that's a little clearer.

Cheers,
  Lee :beers:
