### ISSUE TITLE
Should the code be open-source?

### ISSUE THREAD

**Issue by pksunkara** [github/game-off-2012#18]
Or I can just link to the game in README of my fork?

**Comment by alol** [comment]
The instructions say:

> All entries must be web-based i.e. playable in a browser. HTML5, WebGL, Unity, Torque 3D, Node JS, Flash is all possible - **just be sure the source is made available on your fork**.

So, definitely open-source!

**Comment by jw-00000** [comment]
But does it need to be published under an open source license? You could make the source code of your game available, but still copyrighted. Is that allowed?

**Comment by wildlyinaccurate** [comment]
"Open-source" simply means that the source code is publicly available. Use whatever license you like.

**Comment by NightKev** [comment]
As per #6, there is no restriction on licensing.

**Comment by leereilly** [comment]
Ah the others have said, yeah, the source code for your your game should be available for viewing in your forked repository. You can use whatever license you like.

Cheers,
  Lee :beers:
