### ISSUE TITLE
Repo name - game-off-2012 ?

### ISSUE THREAD

**Issue by ondras** [github/game-off-2012#19]
Does the forked repo need to be named "game-off-2012", or can we rename it to better reflect the game's name?

**Comment by leereilly** [comment]
Good question. Yes, you can rename the repository. Changing it to the game's name makes perfect sense. We'll see all the [forked repositories](https://github.com/github/game-off-2012/network) regardless of what they're called.

Cheers,
  Lee :beers:

**Comment by corroded** [comment]
I see it has 953 forks(so far) but scrolling down that network graph shows that not all 953 are there? I guess you can only see forked repos with actual commits, right? (just checking)

**Comment by bui** [comment]
@corroded - You can see all forks on the [members page](https://github.com/github/game-off-2012/network/members).

**Comment by Seldaek** [comment]
@leereilly just for information, how do you plan on going through the 1300+ forks? :)

**Comment by leereilly** [comment]
Good question! I'm using the GiHub API to gather all the forks, populate a spreadsheet, a seed little app for the judges with links/screenshots, etc. I'm not sure how many of those forks will actually have games in the end - there are only about 100 with added content as of right now.

Cheers,
  Lee :beers:

**Comment by Seldaek** [comment]
@leereilly ok cool. I hope you will make the list of "active" repos available on december 1st - I was curious to see what others have been up to but by poking repos at random I only managed to find a couple working games.

**Comment by robbestad** [comment]
It would be great to see a list of active repos. I found a few by chance, but it's hit and miss just clicking on the links in the member section.

**Comment by gelisam** [comment]
Since the fact that this thread was just closed sent me a notification which might bring others in this thread here, I thought I would point out that I did publish such as list of playable games back in 2012: http://gelisam.blogspot.ca/2012/12/every-single-game-from-github-game-off.html
