### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by sirpengi** [github/game-off-2012#20]
Are there some set of browsers/version the game needs to support? Will the judges respect a request like "use latest chrome stable"?  I personally don't want to think too hard about IE on my projects-for-fun, and some devs might want to use NaCl.

**Comment by leereilly** [comment]
Ideally, the game should be playable in all browsers, but that's not a strict rule :smile: 

If there are any special instructions please just add them to the README. Asking judges to use the latest version of Chrome or Firefox is perfectly OK. Asking to use an older version that we'll have to go out and find... probably not.

Cheers and good luck!
 Lee :beers:
