### ISSUE TITLE
No platform requirements?

### ISSUE THREAD

**Issue by AMetnik** [github/game-off-2012#21]
ei. I can make a HTML5 app on android, which uses specific things from the android OS ?

**Comment by wildlyinaccurate** [comment]
The rules state:

> All entries must be web-based, i.e. playable in a browser.

I would interpret "a browser" as "a desktop browser".

**Comment by quanticle** [comment]
Right, but that's still ambiguous. If I make a game using, e.g. Chrome's NaCl, does that count as web-based, even though it'll only run in Chrome? And, on the other side, does my game have to be compatible with older browsers like Internet Explorer 8, for example?

I think a platform compatibility list (i.e. "you must test your game with the following browsers") would be helpful.

**Comment by leereilly** [comment]
Ideally, it'll should compatible with one or more of latest stable browsers like Chrome, Firefox, Safari, Internet Explorer. If it's only playable in one, just make a note of it in your repository README files. Chrome's NaCl is fine too.

Cheers,
  Lee :beers:
