### ISSUE TITLE
Is it okay if the idea of the game is not original?

### ISSUE THREAD

**Issue by AmaanC** [github/game-off-2012#22]
For example, if I was to remake an iOS or Android game using web technologies? Wouldn't reuse any artwork or sounds, just the concept of the game. Is that okay?

**Comment by NightKev** [comment]
As long as you're not breaking copyright, you should be fine.

**Comment by AmaanC** [comment]
Any pointers on how to check if I'd be breaking any copyrights if the developer(s) of the game doesn't respond?

**Comment by leereilly** [comment]
I agree with @NightKev :+1:
