### ISSUE TITLE
Can we use Octocat (as an art asset)?

### ISSUE THREAD

**Issue by dave-irvine** [github/game-off-2012#23]
Having read the terms here: http://octodex.github.com/faq.html it's looking like we can't use Octocat for much! Is there an exception for this GitHub sponsored gamejam?

**Comment by cameronmcefee** [comment]
Hi @dave-irvine,

Thanks for checking in with us! The Golden Octocat Rule is this: Octocats may only be used in contexts where Octocat = GitHub. In your particular case, if the character is one that when talked to says something like "Check out this game on GitHub" (similar to how BrowserQuest did it http://browserquest.mozilla.org/) that would be totally admissible. If, however, you would like to use it as your protagonist or any story-critical character, it's probably not going to work out, unfortunately.

**Comment by dave-irvine** [comment]
Oh darn, it was going to be a playable octocat. :( Thanks for the reply anyhow!

**Comment by conzett** [comment]
Does this include substantially derivative or reimagined / reconceptualized versions of the Octocat like Sirron Norris' ?

**Comment by cameronmcefee** [comment]
I'd highly encourage people to strive to create brand new characters of their own. This is a great opportunity to creative. 

As to the question at hand, rule applies to the spirit of the Octocat, not just the direct likeness. The golden rule is that the Octocat must == GitHub in its usage, otherwise it is not considered fair use.

If your question is whether the Sirron Norris octocat is a breach of copyright, his was commissioned by GitHub.

**Comment by conzett** [comment]
No, I realize Norris' was commissioned, I was just using it as a reference point. Anyway, that clarifies it for me. I don't think it's an odd question or an issue of creativity though. It is the "Github" game off after, it seems natural for people to want to use fanart of the little guy in a Github themed game.

**Comment by cameronmcefee** [comment]
@conzett Nope, not an odd question, you're right. Unfortunately copyright is a pretty fickle business. We already ride a pretty grey area by letting people reproduce it as much as we do, so there's a lot of tricky back and forth on the subject. While we sadly have to shoot stuff down in a full fanart context (such as primary characters, etc), we still do love it when people create custom Octocats that fall within the usage guidelines.

**Comment by conzett** [comment]
@cameronmcefee Totally understandable, you have to protect your mark.

Perhaps we'll go with an original character based on another merge strategy: Subtreebeard an ent known for his modified recursive magic :wink:

**Comment by cameronmcefee** [comment]
Haha, I wholeheartedly support this.  

## 

Cameron McEfee
Pixels at GitHub (http://www.github.com)

**Comment by arbieo** [comment]
As per the Octocat == Github, can we use octocat as an icon to represent the Git Game Off?

**Comment by cameronmcefee** [comment]
@arbieo I think that would depend on the specific context. I could see it going either way.
