### ISSUE TITLE
Engine/Library Rule 

### ISSUE THREAD

**Issue by drabiter** [github/game-off-2012#25]
Hi git,

I believe that GGO12 accept all kind of programming language as long it meets written criteria. How about rule on using third party libraries (like LibGdx) or engine (like Unity)? Are they allowed?

Thank you.

**Comment by leereilly** [comment]
That's perfectly acceptable. As long as you make the source available (barring any commercial 3rd party dependencies) on the repository and link to a URL where the game can be played. 

Cheers,
  Lee :beers:
