### ISSUE TITLE
What constitutes a team?

### ISSUE THREAD

**Issue by leaveluck2heaven** [github/game-off-2012#26]
I have a friend who can't commit alot of time to the project but took pictures of some of his art. He gave them to me and said I could do what ever I want with them. Going to be coding alone. Should i submit as a team or as an individual???

**Comment by drabiter** [comment]
I also have same situation. Only me who will code and use git apparently. I want to know the answer too.

**Comment by NightKev** [comment]
#14 seems to answer this already.

**Comment by leereilly** [comment]
You can submit as an individual. 

It's always nice to give credit where credit's due, so you could consider adding a section in the README saying where the artwork came from, and perhaps link to your friend's web site. This is optional.

Cheers,
  Lee :beers:
