### ISSUE TITLE
Do assets need to be open source / creative commons?

### ISSUE THREAD

**Issue by anthonyfinch** [github/game-off-2012#28]
Although it is clear that the code should be open source and available through the entrants' repo, what about assets? Do these have to have similarly permissive licenses? I am mainly thinking of sound. Obviously it's completely trivial to load them from another location (so they are not included in the repository) but is this permitted?

**Comment by ShepAlderson** [comment]
I'd say this is fine. In fact, git doesn't tend to play nicely with binary assets, so linking them in from another location should be ok.

@leereilly should probably weigh in as a judge.

**Comment by leereilly** [comment]
Ideally, I'd like to see _all_ of the assets in the GitHub repository. If there's a good reason not to include it in the repository, I'd entertain it though.

Cheers,
  Lee :beers:

**Comment by Finjitzu** [comment]
I'm using Unity, I'm totally ok with sharing any assets I make. Code, 3d models and animation. But any out of the box assets or paid assets I shouldn't be sharing. Will I still be able to compete if the COMPLETE source isn't pushed?

**Comment by leereilly** [comment]
Of course! If you could just leave a note in the README what 3rd-party/paid dependencies are missing, that'd be awesome!

Cheers,
  Lee :beers:
