### ISSUE TITLE
Is using a commercial game engine (such as ImpactJS) okay or are entries limited to F/OSS game engines only?

### ISSUE THREAD

**Issue by s3thi** [github/game-off-2012#3]

**Comment by leereilly** [comment]
That's fine. It'd be great if you could add a note in the README about any dependencies.

Cheers,
  Lee :beers:

**Comment by dclowd9901** [comment]
General: Make sure you remember, per the license, you don't distribute the ImpactJS Engine itself. Here's a .gitignore you can use:

```
index.html
lib/impact
lib/weltmeister
tools/
weltmeister.html
```

**Comment by s3thi** [comment]
Aye. Thanks for the tip, dclowd9901.
