### ISSUE TITLE
impactJS usage as framework

### ISSUE THREAD

**Issue by ibnutri** [github/game-off-2012#31]
perhaps I'm gonna use impactJS as framework for game off 2012
problem is the license won't allow adding impactjS itself on the repository

but other script would be okay (gameplay script)

am i eligible for the hackaton?

**Comment by leereilly** [comment]
Using impactJS is fine. If there are any dependencies on 3rd-party frameworks like this, you can just make a note of it in the README. That'll let the judges know that what you used.

If you'd like other people to be able to fork your game and contribute to it, I'd recommend adding a quickstart guide e.g. (1) purchase Impact, (2) place it directory X, etc. Just a suggestion.

Cheers,
  Lee :beers:

**Comment by ibnutri** [comment]
Thanks,
sorry for reposting same question
