### ISSUE TITLE
Multiple game entries? 

### ISSUE THREAD

**Issue by corroded** [github/game-off-2012#33]
Is it possible to have multiple game entries? Like if you have 3 simple games, can you submit each game using a different team/individually? Also, what if your team can make 2 mini games, will that count as well? (fork it twice? or create a new free organization and fork again?)

**Comment by leereilly** [comment]
You can have one individual submission, and as many team submissions as you like. For now, please use a different organization for each fork.

Good luck!

Cheers,
  Lee :beers:
