### ISSUE TITLE
Is a Chrome Extension accepted?

### ISSUE THREAD

**Issue by jellea** [github/game-off-2012#34]
Hey, I just wanted to check before I'm putting a lot of effort into the challenge. I want to build a layer upon Github's Gist interface by using a Chrome extension. I'm not sure if you accept a web browser extension as a web-based game. More details [here](https://github.com/jellea/game-off-2012)

Thanks in advance!

**Comment by leereilly** [comment]
Sounds interesting! Chrome extensions are fine. Please just be sure to make a note of it the README along with any additional setup / configuration required.

Good luck!

Cheers,
  Lee :beers:
