### ISSUE TITLE
Old project that just started being coded gameplay wise

### ISSUE THREAD

**Issue by DreadKnight** [github/game-off-2012#35]
I have a free open source game project (www.AncientBeast.com) here on github https://github.com/FreezingMoon/AncientBeast

It's a rather old project but only recently it took off regarding coding, since it doesn't uses an existing 3rd party engine and barely any libs at all and it was really hard finding a good lead programmer.

Developer preview playable over at http://AncientBeast.com/combat 
Keep in mind it's very early and it will get into the contest theme better pretty soon.

We don't really care for winning but we thought that this contest could mean free exposure for the project, which might improve it's fate a lot.
1. Can Ancient Beast participate? It's a very serious project that won't get laid down anytime soon, unlike most of the games that are made specially for this competition. It only started to be somewhat playable just a few days before you announced this contest and it still has a long way to go.
2. Since the project coding is done already via Github, could we avoid having to push the code to the contest fork? Or perhaps having it as a submodule would be enough?

**Comment by DreadKnight** [comment]
I don't know why I'm even wondering about question 1. It's the same thing as the project would have just been started but it was using existing assets under a creative commons license. So moving on to question 2, can I just link to the original repo? Well, the time I spent writing this stuff, I could have learned about submodules or just copy-pasted and pushed the code to the contest-fork branch as well.

**Comment by mvasilkov** [comment]
From what I can tell, [the project started in mid-2011](https://github.com/FreezingMoon/AncientBeast/commits/master?page=20). IMO this would be unfair to those who just came up with the concept 2-3 days ago.

**Comment by DreadKnight** [comment]
Ancient Beast is way older. I thought of design, made website and some assets, with help and contributions from others.
The thing is I didn't managed to find a coder for the gameplay up until a few days ago and most assets won't make it into the project anyway for at least a few more months. The project was never played by people and it didn't participated in any contests, so what about fair for me? Lots of other people think of all sorts of projects, but they don't actually do them, at least nothing worthy comes out of their ideas, because they're not motivated enough, don't take the time to make things happen or only consider the financial aspect and don't want to help out other projects because it will probably not get them any financial rewards of profit cuts and so on. It's not like all games are totally original ideas anyway, every piece of art and whatever gets inspired from left and right. As far as I'm concerned, other projects in the competition could use assets and code from Ancient Beast, as long as they don't copy cat the whole project.

So I put a lot of thought into this project, why wouldn't it be fair to have a chance at being rewarded for it in favor of people who didn't do crap before the competition? Anyway, I don't really care about winning, like I said, just want to the project be part of this if it's not too much to ask considering the project is foss code and art wise and me and contributors are giving so much for free. On top of that, there aren't any rules saying "you must have only moved a finger regarding your project right after the contest was announced". Anyway, I pity the people that just start a project for the sake of winning some Apple merchandise, because for me it's really not about that. Most of the competition entries won't really get anywhere, while I'll work on my project many years ahead in order to make it awesome and world wide popular no matter what it takes!
