### ISSUE TITLE
Does "web-based i.e. playable in a browser" mean no server-side tech?

### ISSUE THREAD

**Issue by andrewhavens** [github/game-off-2012#4]
I was thinking about building a multi-player game, but that would require some server-side technologies for communicating between players. Is this allowed?

**Comment by leereilly** [comment]
Server-side technologies are OK. If you have to create a separate repository for server-side stuff, please just be sure to make a note of it somewhere in your README file.

Thanks and good luck!

Cheers,
  Lee :beers:

**Comment by ShepAlderson** [comment]
Yeah, the objective is to allow anyone to be able to play the game. No one wants to have to juggle making things compile or troubleshoot things to test out a game. :)

**Comment by TheHippo** [comment]
So providing source code for server and a running instance would be fine?
