### ISSUE TITLE
Can we overwrite the README with the game's instructions/description or do we create a new file for that?

### ISSUE THREAD

**Issue by corroded** [github/game-off-2012#40]

**Comment by leereilly** [comment]
Good question. YES, please overwrite the README file. Please also be sure to edit your forked repository's description and website field as shown here:

![](https://img.skitch.com/20121010-x2ecpu95fi91us6hbfehg2dgit.png)

Cheers,
  Lee :beers:

**Comment by josefnpat** [comment]
How about the repo name, or would it no longer show as a fork then?

**Comment by leereilly** [comment]
Yup, you can rename the repo too - it'll still show up as a fork.

Cheers,
  Lee :beers:
