### ISSUE TITLE
On pre-existing projects

### ISSUE THREAD

**Issue by mvasilkov** [github/game-off-2012#41]
**Q:** are pre-existing projects (established well before the game-off started) allowed?

This isn't explicitly outlined in the README, and e.g. #35's starter says that's perfectly normal for a [16-months-old project](https://github.com/FreezingMoon/AncientBeast/commits/master?page=20) to take part on the same grounds as 4-days-old ones.

Maybe I'm missing something and this really is a non-issue, but can awesome judges please clarify?

(This is similar to #5.)

**Comment by leereilly** [comment]
Thanks for your question. We're cool with using 3rd party engines, libraries, assets, etc. To an extent, we're fine with people including a game engine they've written previously, but taking a project that's a few months/years in development and rehashing it / updating would be be unfair to other participants.

I'll make sure we clarify this in the _next_ Game Off so it's not such a grey area. AncientBeast looks great BTW :metal:

Cheers,
  Lee :beers:
