### ISSUE TITLE
Are GitHub icons allowed as game assets?

### ISSUE THREAD

**Issue by rschmitty** [github/game-off-2012#44]
https://github.com/styleguide/css/7.0

I did not see any mention of license restrictions that are shown for Octocats

**Comment by szeryf** [comment]
+1, just came here to ask the same question

**Comment by ozh** [comment]
Issue #23 seems to partially cover this (the octocat)

**Comment by szeryf** [comment]
Yes, I read about the Octocat, but since the game is supposed to make use of git/github concepts, it would be nice if one could use github icons to visualize these concepts.

**Comment by rschmitty** [comment]
@ozh I didn't even notice the Octocat icons previously.  I was more asking about the non-octocats, sorry for not being clear in op.  I'm interested in fork/merge/pull-request and the like

**Comment by leereilly** [comment]
That's a great question. Use of our Octicons here isn't permissible here unfortunately, but we'd love to see your interpretation of the buttons and the actions they represent.

Cheers and good luck!
  Lee :beers:

**Comment by ozh** [comment]
@rschmitty @szeryf take a look at http://fortawesome.github.com/Font-Awesome/ it's, well, awesome :)

**Comment by leereilly** [comment]
Great suggestion @ozh - thanks!

**Comment by rschmitty** [comment]
Thanks @ozh , @leereilly
