### ISSUE TITLE
What happens if people fork the entries of others during the competition?

### ISSUE THREAD

**Issue by eric-wieser** [github/game-off-2012#48]
What happens if someone forks what would be the winning entry minutes before the end of the competition, and adds a small improvement?

Technically, they have the better game, but it feels cheap to pull the prize from the person who put all the work in.

**Comment by leereilly** [comment]
Hi Eric,

Good question. Only direct forks of [github/game-off-2012](https://github.com/github/game-off-2012) will qualify for entry. 

Cheers,
  Lee :beers:

**Comment by jlongster** [comment]
It would still be trivial to fork the official one but copy somebody else's.

I think that's just the nature of doing an open competition though. If it really came down to a dispute I'm sure you could compare commit histories and see who the real author is.

**Comment by drabiter** [comment]
Or push your works on last minutes (Nov 30 11.55pm) but it's risky :)
