### ISSUE TITLE
How can you use an existing repository as an entry ?

### ISSUE THREAD

**Issue by phtrivier** [github/game-off-2012#51]
Hi 

Here's my question : 
- I forked the game-off-2012 repository
- I created another repository for my tentative entry
- I want the judges to be able to see my stuff in the end (if i get the time to do something ;) )

What is the best way to proceed ? 
- copy all the code from my repository, when it's done, to my fork of game-off-2012 ? 
- add the fork's repository as a remote for my existing repository (and push there ?)
- any other github trick that I'm not aware of ? 

Thanks

**Comment by leereilly** [comment]
Hi there,

It's entirely up to you. As long as all the code's there with a link to the playable game in repository's website field, that's all that's required. You can even add it as one large commit.

Cheers,
  Lee :beers:
