### ISSUE TITLE
audio copyrighting

### ISSUE THREAD

**Issue by cathoderay** [github/game-off-2012#52]
I'm not a Phd in copyrighting issues, so I'd like to know from you if I'm doing anything ilegal.
I'd like to add a midi song in my game from an already existing and copyrighted song. Since this is not the original record is it valid to be used?

**Comment by leereilly** [comment]
Good question. I'm not a lawyer, nor do I play on TV, but I'd err on the side of caution and only include media that you know you're licensed to use.

Cheers,
  Lee :beers:
