### ISSUE TITLE
What is the recommended size of the game resources ?

### ISSUE THREAD

**Issue by sdrdis** [github/game-off-2012#56]
What is the recommended size of the game resources? 5MB? 20 MB? Is there any hard limit ?

Thanks!

**Comment by leereilly** [comment]
Great question! There's no hard limit, but if you're repository's _waaaaaay_ over 1GB you may get a friendly email from out supportocats prompting you to take some action.

Cheers,
  Lee :beers:

**Comment by ididntknowicoulddothatXD** [comment]
:beers:
