### ISSUE TITLE
Can I embed YouTube in my game?

### ISSUE THREAD

**Issue by ghost** [github/game-off-2012#58]
I'm poor musician and I can't even compare to artist/s who created music that perfectly fits my game. I don't own rights to distribute their music, so I decided to embed a hidden chromeless YouTube player as a music source in my game. Is it a problem?

**Comment by leereilly** [comment]
That's an interesting approach. This is really a question for [YouTube Support](http://support.google.com/youtube/?hl=en) though.

Cheers,
  Lee :beers:
