### ISSUE TITLE
Is it possible to use a different language to incorporate the concepts into the game?

### ISSUE THREAD

**Issue by corroded** [github/game-off-2012#60]
Something like "tinidor" for forks (tagalog) or whatnot. Also related, if I don't plan to have flashy graphics, is the storyline enough into tying the concept to the game? Or do we really need to actually show the graphics of forks/branches etc.?

**Comment by leereilly** [comment]
> Is it possible to use a different language to incorporate the concepts into the game? Something like "tinidor" for forks (tagalog) or whatnot. 

Yes - that's totally fine.

> Also related, if I don't plan to have flashy graphics, is the storyline enough into tying the concept to the game? 

Yes, that's also fine.

Good luck!
