### ISSUE TITLE
Can I push to the repo after December 1st?

### ISSUE THREAD

**Issue by mvasilkov** [github/game-off-2012#63]
I know active development should end before the deadline, but what happens if I push e.g. small bug fix (like forgotten CSS prefix) after December 1st? You won't disqualify for that, right?

Or maybe we should commit to a side branch, leaving master in fixed state as of Nov. 30 23:59?

Since _the end is nigh,_ this is increasingly relevant.

Thank you. :kiss:

**Comment by leereilly** [comment]
That's a great question. If you could wait until pushing to master again until after the winners are announced, that'll make the judges' lives easier. 

Cheers,
  Lee :beers:

**Comment by pkukielka** [comment]
Maybe it's stupid question but I didn't seen any mention about this so far:
what timezone should I use to decide when I can do last commit?

**Comment by mvasilkov** [comment]
@pkukielka any, see #68

**Comment by pkukielka** [comment]
Great, thanks!
Somehow I missed this one.

**Comment by webfacer** [comment]
but could we push now after the competition the READMEmd, because its not a code its just a content?

**Comment by danfischer87** [comment]
Yeah, I second webfacer's question. Can we push to the README.md file?

**Comment by Nek** [comment]
I second that too.

**Comment by leereilly** [comment]
If you could hold off until after the winners are announced, that'd be great.

Cheers,
  Lee :beers:
