### ISSUE TITLE
Custom browser

### ISSUE THREAD

**Issue by davidgomes** [github/game-off-2012#64]
Hello there,

Is it possible I use a custom browser (it's a 10 lines C cross-platform program that uses webkit to display my game).

It's easier for some people and the speed is stabler than on Firefox or IE. For the people who don't use or don't have Chromium/Chrome installed, I have found that shipping a custom super-lightweight browser and writing my game with HTML5/JS is the best way.

People would still be able to play the game on Firefox or Chromium/Chrome, but this would be just a better alternative. I will even provide a .exe for Windows users a  GNU/Linux build too, I just need to know if I can do this.

Thanks.

**Comment by leereilly** [comment]
Hi there,

That sounds interesting - I'd love to see it! As long as it's still playable in the other browsers, it's perfectly acceptable.

Cheers,
  Lee :beers:
