### ISSUE TITLE
judging a multiplayer game

### ISSUE THREAD

**Issue by jlongster** [github/game-off-2012#66]
I'm developing a multiplayer first person shooter. If a judge happens to join when nobody else is playing, will you guys be open to asking other judges/coworkers to jump on to play the game?

If not, should I develop some basic AI so that at least you could play some?

Also, on the off-chance that there are too many players, will you guys be willing to wait for a free space?

**Comment by leereilly** [comment]
If at all possible, just leave a note of this in the main game screen / README and we can make special arrangements if there are no other players / free slots available.

Cheers,
  Lee :beers:
