### ISSUE TITLE
Messing with github: a clone of deleted repo

### ISSUE THREAD

**Issue by lrem** [github/game-off-2012#67]
I had the idea of writing a game with my wife. Unfortunately, she got pressed in her day job and could not join. So it first started as Modrzejewscy/kobo-san, then I forked it as lrem/kobo-san, then deleted the first repository.

Now, I've read that you accept only direct clones from github/game-off-2012. So my new repo should not count... But on the other hand, as the first one is gone, it's displayed as if it was cloned from github/game-off-2012 and displays nicely in the network.

Should I do something to remedy the situation, or just leave it as it is?

**Comment by leereilly** [comment]
Hi,

Nope you're good to go [lrem/kobo-san](https://github.com/lrem/kobo-san) is participating. Just be sure to attach a URL and a short description like so:

![](https://img.skitch.com/20121010-x2ecpu95fi91us6hbfehg2dgit.png)

Cheers and good luck!
 Lee :beers:
