### ISSUE TITLE
Exact deadline with timezone?

### ISSUE THREAD

**Issue by jlongster** [github/game-off-2012#68]
I'm just curious, as it looks like I'll be really crunched to get my game done by the deadline. Is the deadline 12:00 AM Dec 1st, PST? I don't see a timezone anywhere in the blog post.

**Comment by leereilly** [comment]
That's a great question. I should have thought of that when publishing the blog post :trollface:

Dec 1st 12:00 AM for whatever timezone you're in is fine by me. Judging won't start until late Saturday Dec 1st...

Cheers,
  Lee :beers:

**Comment by eric-wieser** [comment]
> We've extended the deadline to Dec 1st 12:00 PST

To confirm, this means noon?

**Comment by leereilly** [comment]
Yup, noon :+1:
