### ISSUE TITLE
What criteria will the judges choose winners based on?

### ISSUE THREAD

**Issue by roryokane** [github/game-off-2012#7]
What criteria will the judges choose winners based on?

I could imagine all of these possibly being criteria: “the game…”
- is fun to play
- is “cool”
- is closely enough related to the themes
- is not too literally related to the themes
- has beautiful graphics or a fitting art style
- provokes thought
- teaches you something
- has well-organized code
- contributes new, useful code to the open-source community

What are the actual criteria judges will look at? Do the criteria have different weights/importance (different point values)?

**Comment by ekunuke** [comment]
It's incredibly tough to judge a video game as whole, especially considering the multifaceted nature of development. Ludum Dare tries to do judging through a bunch of individual categories ( http://www.ludumdare.com/compo/ludum-dare-24/?more=1 ), and although it isn't a perfect system, I'm hard-pressed to come up with a better as-objective-as-possible way to judge games.

**Comment by leereilly** [comment]
Not gonna lie - I'm probably not going to look at the source code  unless it's neck and neck between two entries.. I can't speak for the other judges, but I'll ask them to chime in here.

Personally, I'm just looking for games that are _just_ fun to play. We do have a number of categories in mind, but didn't want to commit to them until we see the actual entries. There'll very likely be one for best graphics, best sound, most innovative, etc. No promises on what the actual categories are right now though.

Things that are likely to catch my attention are repos with nice + concise READMEs making great use of one or more open source libraries/frameworks. I don't really care how closely/loosely the entries relate to the theme.

I did have a rather elaborate judging system in mind with points/weights, but my friends involved with the Global Game Jam offered some great, very similar advice to @egpaik's. The actual judging process isn't concrete yet. I'll provide details when it's set in stone...
