### ISSUE TITLE
"This repository is temporarily unavailable."

### ISSUE THREAD

**Issue by notsimon207** [github/game-off-2012#72]
I'd really like to enter my game into the competition, but the repository seems to be unavailable at the moment. 
Would it perhaps be possible for me to enter into the competition in some other way, like emailing the link to my game and the source code trough to some one?
Thanks in advance.

**Comment by leereilly** [comment]
Hi there,

We were having some network/fileserver issues earlier on today ([details here](https://status.github.com/)), but everything is back to normal. I [extended the submission deadline](https://github.com/blog/1336-game-off-deadline-extended) until Dec 1st 12:00 PST for people who happened to encounter this...

I see your forked game-off repository @ https://github.com/notsimon207/game-off-2012, but it looks like all of your code is at https://github.com/Fountai2/HardcoreParkour. You should commit/push all of the code in https://github.com/Fountai2/HardcoreParkour to https://github.com/notsimon207/game-off-2012 to ensure that your entry is judged and eligible for the prizes.

Cheers and good luck!
  Lee :beers:
