### ISSUE TITLE
Did I submit correctly?

### ISSUE THREAD

**Issue by Fountai2** [github/game-off-2012#74]
I am not sure if everything I put up is right or not, how will I know if everything got submitted?

**Comment by bui** [comment]
You created a new repository (https://github.com/UXLab/github-game-off-2012) which doesn't qualify you. You need to fork this repository (https://github.com/github/game-off-2012) by clicking the Fork button at the top of the page, and push your changes to that repo.

**Comment by gbatha** [comment]
If we see ourselves in the network/members list of the (https://github.com/github/game-off-2012) repo, that means we did it correctly, yes? I am assuming that is the list the judges will be pulling from.

**Comment by leereilly** [comment]
Hi there,

@Fountai2 follow @bui's advice and you'll be good to go.

@gbatha correct! Direct forks of https://github.com/github/game-off-2012 with URLs recorded in the repository at the top will be judged.

Cheers,
  Lee
