### ISSUE TITLE
Allow people to filter out and see valid ggo12 entries (solution included)

### ISSUE THREAD

**Issue by pkukielka** [github/game-off-2012#76]
I made quite simple viewer for ggo12: http://pkukielka.github.com/ggo12-viewer/
It shows all entries with proper homepage. There is also some very basic filtering added.
Maybe it's not really an issue, but I thought it could be useful for some people.

**Comment by sdrdis** [comment]
Exactly what I needed! Thanks!

**Comment by sdrdis** [comment]
You just have a console.log somewhere (could block the page on some browsers)... It would be nice also to have the exact number of entries displayed somewhere (should be easy :)) : it's at the moment 182.

**Comment by mvasilkov** [comment]
Another sleepless night ._.

Thanks @pkukielka ^_^

**Comment by pkukielka** [comment]
@sdrdis Fixed, thanks :)

@mvasilkov You are welcome :D

The only problem with this viewer is that repositories list is not fetched from github but appended as static asset.
It is because of github limitations on the amount of API calls for not authenticated users.
But it shouldn't matter too much because after deadline new entries won't be valid anyway.

**Comment by bui** [comment]
Thanks :)

**Comment by leereilly** [comment]
Great idea @pkukielka - thanks!

**Comment by pkukielka** [comment]
I updated entries list (I guess last time, because deadline is over) and added sorting.

**Comment by pkukielka** [comment]
Added facebook likes (pull request by @Zolmeister) and sorting by likes.

**Comment by webfacer** [comment]
awesome thing !!!  can you give the links the property `target="_blank"` to open it in a new tab. that would be awesom awesom! :+1:

**Comment by pkukielka** [comment]
@webfacerI didn't seen this as a problem because I'm always opening new pages by clicking with scroll button so it's equally easy. But sure, it sounds reasonable and is already done ;)

**Comment by webfacer** [comment]
thx. it wasn´t a big problem :) but id liked to see all with a single klick just using mouse.

**Comment by gbatha** [comment]
This is great! Would it be possible to add the username (or even just an incrementing integer) as the id for each li? That way people could direct link to their games like http://pkukielka.github.com/ggo12-viewer/#gbatha

**Comment by pkukielka** [comment]
@gbatha Sounds nice, I'll do it when I'll be in home ;)

**Comment by pkukielka** [comment]
@gbatha Sorry for long waiting time, I was extremely busy this weak :(
It should be working fine now:

http://pkukielka.github.com/ggo12-viewer/#pkukielka

**Comment by gbatha** [comment]
@pkukielka this works wonderfully! I apologize for the terribly belated reply, but thank you! :)
