### ISSUE TITLE
When will the winners be selected?

### ISSUE THREAD

**Issue by Draknek** [github/game-off-2012#77]
I can't see anywhere that states how long the judging period is.

Thanks!

**Comment by bui** [comment]
I'd guess as soon as the judges review and choose the winners, but the README says before Christmas.

**Comment by leereilly** [comment]
We should be announcing the winners and runners up be in the next week or two.

Cheers,
  Lee :beers:

**Comment by pkukielka** [comment]
So, should we expect it this week or it's still work in progress? ;)
