### ISSUE TITLE
Is it ok if we commit a change to make our site stable?

### ISSUE THREAD

**Issue by heynemann** [github/game-off-2012#79]
Our application is hosted at http://fightcodegame.com. We are experiencing a load that is way above whatever trafic we expected.

Right now we have had near 100k page views since saturday. In the rush for the contest, we forgot to put static files in a "/public" folder.

Because of that we need to restart our server every 10-30 minutes. Do you think it would be ok for us to commit just that change. It won't affect anything in our game. It's just a stability issue.

Thanks again for the opportunity to participate in this amazing contest.

Cheers,
Bernardo Heynemann

**Comment by leereilly** [comment]
By all means - that's fine. I :heart: your entry BTW!

Cheers,
  Lee :beers:

Sent from my iPhone

**Comment by heynemann** [comment]
Thanks a LOT! Already fixed.

Cheers,
Bernardo Heynemann
