### ISSUE TITLE
meta-issue: move judge self-answers from Issue descriptions to comments

### ISSUE THREAD

**Issue by roryokane** [github/game-off-2012#8]
Issues #1 and #2 are written by [leereilly](https://github.com/leereilly), one of the judges. Currently, the answers to those questions are in the description of the Issue. I was confused by that – I thought to myself, _if the asker knew the answer already, then why did he ask it? And how did he know the answer, anyway – he’s just some question-asker, not a judge._ As it turned out, he is a judge – but I had to look at the official list of judges to find that out.

It would be clearer to edit the description of those Issues (#1 and #2) to blank and have the judge post the answer in a comment. That would clearly separate the question and the answer.

**Comment by ShepAlderson** [comment]
Thanks @roryokane.

I've went and fixed them.

**Comment by leereilly** [comment]
Good idea - thanks!  :+1:
