### ISSUE TITLE
hi again, we found an issue that makes our site VERY unstable

### ISSUE THREAD

**Issue by heynemann** [github/game-off-2012#80]
Hi again,

Our project is http://fightcodegame.com

We would like to commit a small patch (that does not change the website behavior at all) that will make the website A LOT more stable.

We found an issue where users put in malicious code that can take the server down.

Do you think it would be ok if we just commit that change?

Cheers,
Bernardo Heynemann

**Comment by heynemann** [comment]
Btw, I'm only asking because we are under a much heavier load than we anticipated. We are 200k page views and rising fast.

**Comment by leereilly** [comment]
Replied via email a couple of weeks ago. Closing :)
