### ISSUE TITLE
Missing Coderwall Badge

### ISSUE THREAD

**Issue by josefnpat** [github/game-off-2012#83]
Hey Guys,

My buddy and I @peterrstanley (https://github.com/peterrstanley) participated in the game off with this submission:

https://github.com/asswb/game-off-2012

From what I can tell, neither him or myself have gotten the badge promised for participating.

How does this work?

**Comment by peterrstanley** [comment]
Hey Guys,

josefnpat is correct; at this time, I also have not received the Coderwall badge promised. If you could let us know how it all works, that would be great.

**Comment by leereilly** [comment]
Hi there,

I've reached out to the fine folks @coderwall to see if we can get this resolved. Stay tuned...

Cheers,
  Lee :beers:

**Comment by mdeiters** [comment]
Hey, @coderwall here... we are looking into why a few people don't have the badge. We'll keep you posted.

**Comment by peterrstanley** [comment]
Hey guys,

Have you been able to figure out the why @josefnpat and I never received the Coderwall badge. I know Coderwall was looking into it, but I haven't heard from them since their post. I was just wondering the status of the issue.

**Comment by beghbali** [comment]
I went ahead and added you guys manually. You were not included in the initial list we got from Lee so that's why you were not awarded automatically. cheers.

**Comment by josefnpat** [comment]
@beghbali Much appreciated!

**Comment by leereilly** [comment]
@beghbali some of the participants on the initial list at https://gist.github.com/1f40f42630ea9f04cde0 (the ones obtained via the API) will be Organizations as opposed to Users. Do you need me to send you a list of those Organizations and their Users... or does Coderwall have this magic already?

**Comment by beghbali** [comment]
that magic is not there yet, if you have the org users' usernames, I'll add
them in. we'll support orgs soon.thanks

On Thu, Jan 31, 2013 at 12:55 AM, Lee Reilly notifications@github.comwrote:

> @beghbali https://github.com/beghbali some of the participants listed
> at the bottom of https://gist.github.com/1f40f42630ea9f04cde0 (obtained
> via the API) will be Organizations as opposed to Users. Do you need me to
> send you a list of those Organizations and their Users... or does Coderwall
> have this magic already?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/game-off-2012/issues/83#issuecomment-12933188.

## 

Bashir Eghbali

bashireghbali.com
linkedin http://www.linkedin.com/in/bashireghbali

**Comment by beghbali** [comment]
@leereilly let me know if you have a flat list of participants and their non-org accounts and I'll plug them in so everyone gets the badges. thanx.

**Comment by leereilly** [comment]
@beghbali I updated the list at https://gist.github.com/leereilly/1f40f42630ea9f04cde0 with all of the contributors to  individual and organization forks. Thanks!

**Comment by beghbali** [comment]
great! thanks. I'll take care of these.

On Thu, Feb 21, 2013 at 5:32 PM, Lee Reilly notifications@github.comwrote:

> @beghbali https://github.com/beghbali I updated the lists at
> https://gist.github.com/leereilly/1f40f42630ea9f04cde0 with all of the
> contributors to individual and organization forks. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/game-off-2012/issues/83#issuecomment-13923917.

## 

Bashir Eghbali

bashireghbali.com
linkedin http://www.linkedin.com/in/bashireghbali

**Comment by beghbali** [comment]
@leereilly The new list is shorter than the previous one. I do get a different list from the API as well. Just want to make sure that the participant list on the link you sent is the entire list of individuals or it is supplementary to the previous list?

**Comment by leereilly** [comment]
@beghbali you should consider it supplementary - some forks of the original parent repo have since disappeared. The updated list is a list of all _contributors_ (with one or more commits) to all of the existing forks. Thanks!

**Comment by beghbali** [comment]
yeah, we never got around to adding org support.

On Tue, Nov 5, 2013 at 6:56 PM, chocopie notifications@github.com wrote:

> Aw, I just saw the blog update for this year's game-off. My partner and I
> still never received our badges for participating last year, and we're not
> on the list too. Did it turn out to be impossible then, because we entered
> as an 'organisation' instead of as individuals? :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/game-off-2012/issues/83#issuecomment-27837744
> .

## 

Bashir Eghbali

bashireghbali.com
linkedin http://www.linkedin.com/in/bashireghbali

**Comment by chocopie** [comment]
Hehe that's okay. :) These things happen. Thank you for getting back to me.
