### ISSUE TITLE
When's the next game off?

### ISSUE THREAD

**Issue by tybenz** [github/game-off-2012#85]
I recently created a new game called [gitchess](https://github.com/gitwar/gitwar/tree/master/gitchess) and it got me thinking about the game-off. I built a utility called [gitwar](http://github.com/gitwar/gitwar) to be used by all sorts of text-based git-connected 2-player games.

I realize that it wouldn't be within the criteria for the most recent game-off. But it is heavily based on git and GitHub. Just thougt I'd share it.

It would be really cool to have a game-off based on text-based games that let users compete/communicate via git.

Just throwing this out there to see if I get anything back.

**Comment by leereilly** [comment]
_Very_ cool - I'll keep my eyes on it!

Please stay tuned to the [GitHub Blog](https://github.com/blog) for details about the next Game Off. I'm a big fan of turn-based strategy games, so maybe I'll use gitwar to submit an entry of my own!

Cheers,
  Lee :beers:
